# Generated by Django 2.2 on 2019-04-22 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190422_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 16, 16, 43, 788301)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
