# Generated by Django 2.2 on 2019-04-22 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190422_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
